### ISSUE TITLE
inspector failure

### ISSUE THREAD

**Issue by chanwilson** [nyu-mlab/iot-inspector-client#3]
MacOS 10.14.4, iot-inspector-client version from 4/1/19.

Network connections via both wifi and usb-ethernet.
start_inspector_mac runs for a bit less than a minute, spawning off an iot-inspector-netdisco or two, then exists.
Perhaps related to multiple NICs in use (on the same network) as well as VPN (tunnelblick) on this system?
Can triage further as needed.

**Comment by kelgazza** [comment]
I got this error when running on the same OS version:

WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: more __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: more __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: more __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: more __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: more __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.
WARNING: more __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.

**Comment by jareau** [comment]
About this in the FAQ: "...it is likely that your router blocks our ARP spoofing attempts, thus preventing IoT Inspector to intercept any network traffic. In this case, IoT Inspector will not work on your network.".

Are there any workarounds for this?

**Comment by crazyideas21** [comment]
> start_inspector_mac runs for a bit less than a minute, spawning off an iot-inspector-netdisco or two, then exists.

@chanwilson IoT Inspector automatically closes within 15 seconds if you don't open inspector.cs.princeton.edu and interact with it. This feature is meant to prevent continuous data collection without users' knowledge. Did you have the inspector.cs.princeton.edu webpage open?

> WARNING: del: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.

@kelgazza I've seen this before. Seems like a `scapy` bug and doesn't appear to affect the functionality of IoT Inspector. Correct me if I'm wrong?

> Are there any workarounds for this?

@jareau Yes, but it's a somewhat complex workaround. You'd need to reconfigure your DHCP server such that the computer running IoT Inspector would become the gateway for the rest of the devices; in this way, all traffic would be routed through the computer.

**Comment by chanwilson** [comment]
@crazyideas21 Yes, upon launching and authenticating start_inspector.app, a Chrome tab is opened to inspector.cs.princeton.edu.  That page never updates, and the tiny status displayed in the upper right corner never changes from "Loading IoT Inspector..." and then times out within a minute.  No data is gathered or displayed on the web page.

**Comment by crazyideas21** [comment]
@chanwilson My guess is that the actual binary of IoT Inspector (not the apple script wrapper) never loaded because you were running a VPN client. I've tested IoT Inspector while running a VPN client myself; `scapy`, Python's packet capturing module, does not work well with the VPN network interface. I suggest you turn off VPN and try again.

**Comment by chanwilson** [comment]
I don't have tunnelblick (VPN) running, but I do have the Docker subsystem running which has created several additional network interfaces... ?

**Comment by crazyideas21** [comment]
@chanwilson That's a likely reason, and I have no idea how to fix `scapy` for your situation. Any ideas would be appreciated!

**Comment by chanwilson** [comment]
Ok, straight up quitting the Docker subsystem didn't help; the `utun0` and related interfaces are still hanging around.  I'll try a reboot later today with Docker disabled and see if that helps any.  

How about being able to specify the interfaces `scapy` listens on?  Heck, just restricting it to the `enXX` interfaces might be good enough.

**Comment by crazyideas21** [comment]
Thanks for the suggestion! Let us fix this issue in the upcoming release.

**Comment by crazyideas21** [comment]
Related report:

Hi [Redacted],

If a user has an existing VPN app installed, IoT Inspector is known to crash within 30 seconds. This problem is probably due to a bug in the code that does not handle VPN's virtual network interface correctly. We will fix this issue.

In the meantime, one way to get around this problem (although not ideal) is for you to completely uninstall your VPN app, so that there'd be no more VPN virtual network interfaces. If you're not comfortable with this approach, consider signing up for our waitlist so that we'll notify you of the next major release:

https://docs.google.com/forms/d/e/1FAIpQLScUSZAscKfc-mmw3yMmItjc46qX2fs-UryMYxwXmJjzf5BuuA/viewform

Let us know if this works.

Cheers,
Danny

**Comment by apschwartz** [comment]
@crazyideas21 , I tried uninstalling my VPN, which was Tunnelblick.  Rebooted.  Ran IoT Inspector again.  Same behavior, browser never redirected, and when tailing the log file the app logs 
[Main] Quit
after about 28 seconds.  Prior messages are primarily [ARP Spoof] and show no obvious error messages.

If/when you are interested, I'd be happy to send log as well as my ifconfig config, and whatever debug data you want.

Looking forward to running the tool at some point!  I will sign up on the next-release list.

Andy

**Comment by crazyideas21** [comment]
@apschwartz Could you send me your log? I'm curious what's going on. Thanks!

**Comment by apschwartz** [comment]
Sure.  Sending via email outside github.

**Comment by apschwartz** [comment]
@crazyideas21, thanks to your suggestions I have found the issue.  Since it could affect others, this was my failure mode:

Configuration:
- Running Google Chrome on a Mac
- Installed EFF's "HTTPS Everywhere" extension

Behavior:
- Run IoT Inspector app.  Browser opens at "https://inspector.cs.princeton.edu/setup" Starting IoT Inspector page.  Page never redirects, just hangs there.
- Clicking on the highlighted link (https://inspector.cs.princeton.edu/) does not help, it just brings back the Starting IoT Inspector page.

Fix:
- While page https://inspector.cs.princeton.edu/setup is displayed in browser:
  1)  Click on chrome HTTPS Everywhere extension.
  2) Select "Disable HTTPS Everywhere on this Site"

- If Dashboard page does not appear, try re-running the app now that HTTPS Everywhere has been disabled for the inspector.cs.princeton.edu site.

**Comment by crazyideas21** [comment]
More useful notes from @apschwartz (copied and pasted from my email correspondence with im):

> Disabling the extension allowed your app to communicate with the browser.  I also found that adding https://inspector.cs.princeton.edu/ to the HTTP Everywhere exclusion list also works, allowing the extension to remain running elsewhere.   The extension shows no errors when running that it's affecting the connection, so one would have to know to add the exclusion.

In response to this report, I've added the "Known Bugs" section on the [download page](https://iot-inspector.princeton.edu/blog/post/getting-started/#known-bugs).
