### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tmpdump (from versions: none) ERROR: No matching distribution found for tmpdump

### ISSUE THREAD

**Issue by maying0120** [nyu-mlab/iot-inspector-client#91]
ERROR: Could not find a version that satisfies the requirement tcpdump (from versions: none)
ERROR: No matching distribution found for tcpdump

anyone meet with this problem?  with MacOS Catalina and python version 3.8.5

**Comment by crazyideas21** [comment]
Try without the `tcpdump` package and report the errors.

**Comment by gmorain** [comment]
Hi, just had the same issue here (MacOS Mojave 10.14.6), solved by removing `tcpdump` as suggested (but since I had already installed scapy (`brew install scapy`) and libpcap (`brew install libpcap`) in the past, I am not sure if other steps are needed for iot-inspector-client to work on a stock machine.

My 2 cents: using virtualenv+virtualenvwrapper helps me keep my system clean. If you also have these packages on your Mac :
```
$ mkproject -p python3 iot-inspector
$ git clone https://github.com/noise-lab/iot-inspector-client.git
$ cd iot-inspector-client/src
# edit requirements.txt to comment (#) tcpdump
$ pip install -r requirements.txt
$ sudo python start_inspector.py
```
